### PR TITLE
First look at Jupyter tutorial

### PR DESCRIPTION
**Pull request by silke**
Mostly small fixes like typos or paths.

### CODE REVIEW

**Review by veit — CHANGES_REQUESTED** [review]
If you are in the First Steps directory, you have to go up two levels to be able to change to the `/data` directory. However, it is confusing that there is also a `/docs/data` directory. We should probably rename the latter, e.g. `handling-data`. What do you think of it?

**Comment by silke** [comment]
Following the tutorial, I started the jupyter notebook in the jupyter-tutorial-main/myproject directory. A ``!pwd`` confirms that it is my working directory and from there the ``cd ../../data`` command fails. If one should be somewhere else in the directory that should be added to the steps to execute.

But I agree that two directories with the same name are confusing so renaming the latter seems reasonable.

**Comment by veit** [comment]
Ok, I accidentally started from `docs/first-steps/example.ipynb` and not from `myproject`. But then there is no `data` directory. Isn’t it easier to change to no other directory but just call curl?

**Comment by veit** [comment]
> But I agree that two directories with the same name are confusing so renaming the latter seems reasonable.

The directory is now renamed `data-processing`.

**Comment by silke** [comment]
Ok, I removed the directory change entirely.

**Pull request merged**
